# Generated by Django 2.2.5 on 2019-09-25 03:47

from django.db import migrations, models
import text.models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='im',
            field=models.ImageField(blank=True, null=True, upload_to=text.models.content_file_name),
        ),
    ]
